version: 2
updates:
  - directory: /
    open-pull-requests-limit: 10
    package-ecosystem: cargo
    rebase-strategy: auto
    schedule:
      interval: daily
      time: "05:00"
      timezone: "Etc/UTC"
  - directory: /
    open-pull-requests-limit: 10
    package-ecosystem: github-actions
    rebase-strategy: auto
    schedule:
      interval: daily
      time: "05:00"
      timezone: "Etc/UTC"
